# Generated by Django 4.0.4 on 2022-04-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0002_alter_rawdata_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='rawdata/'),
        ),
    ]
