# Generated by Django 4.0.4 on 2022-04-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0004_remove_rawdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='title',
            field=models.CharField(default='mydata', max_length=200),
        ),
    ]
