# Generated by Django 4.0.4 on 2022-04-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0006_dataplot_interactions_transitions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.TextField()),
                ('headers', models.TextField()),
                ('ids', models.TextField()),
                ('behaviors', models.TextField()),
                ('categories', models.TextField()),
            ],
        ),
    ]
